expression similarity (of|between|for) %string% and %string%:
	return type: boolean
	get:

		set {_value1} to expr-1
		set {_value2} to expr-2

		set {_words1::*} to split expr-1 at ""
		set {_words2::*} to split expr-2 at ""

		set {_intersection} to 0
		set {_union} to size of {_words1::*} + size of {_words2::*}
	
		loop {_words1::*}:
			loop {_words2::*}:
				if loop-value-1 is loop-value-2:
					add 1 to {_intersection}
					subtract 1 from {_union}
					exit loop
			
		set {_similarity} to {_intersection} / {_union}
		if {_similarity} >= 0.8:
			return true
		else:
			return false